// modules/payment/payment.interface.ts

export interface TWorldPayPayment {
  paymentSessionId: string; // The session ID generated by the frontend SDK
  amount: number;
  currency: string;
  description?: string;
  customerName?: string;
  customerEmail?: string;
  buyerId?: string; // To link to your User model
}

export interface TWorldpayConfig {
  merchantId: string;
  serviceKey: string;
  environment: 'TEST' | 'LIVE';
}